CREATE TABLE upload_header (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    user_id BIGINT
);

-- Таблица для "развернутых" динамических данных (Unpivoted)
CREATE TABLE dynamic_import_result (
    upload_id BIGINT,
    static_code BIGINT,
    column_name VARCHAR(50),
    column_value DECIMAL(10, 2)
);